# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

source ~/.colors.sh
source ~/.git-prompt.sh

# User specific aliases and functions

# Prompt
export PS1="\[$GREEN\]\t\[$RED\]-\[$IBLUE\]\u \[$IYELLOW\]\[$IYELLOW\]\W\[\033[m\]\[$RED\]\$(__git_ps1)\[$WHITE\]\$ ";

alias la="ls -a";
alias ll="ls -l";
alias grep='grep --color=auto';
alias firewallon='sudo /root/bin/firewallon';
alias firewalloff='sudo /root/bin/firewalloff';

