# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

source $HOME/config/colors.sh
source $HOME/config/git-prompt.sh

export GREP_OPTIONS='--color=auto'
export LS_OPTIONS='--color=auto'

# User specific aliases and functions

# Prompt
export PS1="\[$GREEN\]\t\[$RED\]-\[$IBLUE\]\u \[$IYELLOW\]\[$IYELLOW\]\W\[\033[m\]\[$RED\]\$(__git_ps1)\[$WHITE\]\$ ";

alias la="ls -a";
alias ll="ls -l";
alias ld="ls -d";

